const tracks = require("./types/UsersTopItems");

export const spotify = {
  href: "https://api.spotify.com/v1/me/top/tracks",
  limit: 20,
  next: "https://api.spotify.com/v1/me/top/tracks?limit=20&offset=20",
  offset: 0,
  previous: null,
  total: 50,
  items: [
    {
      album: {
        album_type: "SINGLE",
        total_tracks: 1,
        available_markets: ["CA", "US"],
        external_urls: {
          spotify: "https://open.spotify.com/album/7mCzA6gqtv4ZtfInpJXm52",
        },
        href: "https://api.spotify.com/v1/albums/7mCzA6gqtv4ZtfInpJXm52",
        id: "7mCzA6gqtv4ZtfInpJXm52",
        images: [
          {
            url: "https://i.scdn.co/image/ab67616d0000b273e399d960a253b2740b549151",
            height: 640,
            width: 640,
          },
          {
            url: "https://i.scdn.co/image/ab67616d00001e02e399d960a253b2740b549151",
            height: 300,
            width: 300,
          },
          {
            url: "https://i.scdn.co/image/ab67616d00004851e399d960a253b2740b549151",
            height: 64,
            width: 64,
          },
        ],
        name: "Solitude (Felsmann + Tiley Reinterpretation)",
        release_date: "2020-05-14",
        release_date_precision: "day",
        type: "album",
        uri: "spotify:album:7mCzA6gqtv4ZtfInpJXm52",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/63MQldklfxkjYDoUE4Tppz",
            },
            href: "https://api.spotify.com/v1/artists/63MQldklfxkjYDoUE4Tppz",
            id: "63MQldklfxkjYDoUE4Tppz",
            name: "M83",
            type: "artist",
            uri: "spotify:artist:63MQldklfxkjYDoUE4Tppz",
          },
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/01OXxPlQj4h9zfK5qjU96P",
            },
            href: "https://api.spotify.com/v1/artists/01OXxPlQj4h9zfK5qjU96P",
            id: "01OXxPlQj4h9zfK5qjU96P",
            name: "Felsmann + Tiley",
            type: "artist",
            uri: "spotify:artist:01OXxPlQj4h9zfK5qjU96P",
          },
        ],
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/63MQldklfxkjYDoUE4Tppz",
          },
          href: "https://api.spotify.com/v1/artists/63MQldklfxkjYDoUE4Tppz",
          id: "63MQldklfxkjYDoUE4Tppz",
          name: "M83",
          type: "artist",
          uri: "spotify:artist:63MQldklfxkjYDoUE4Tppz",
        },
      ],
      available_markets: ["CA", "US"],
      disc_number: 1,
      duration_ms: 222354,
      explicit: false,
      external_ids: {
        isrc: "GB5SH2000001",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/5SOA0gaKMMp9cgwn3nuwk7",
      },
      href: "https://api.spotify.com/v1/tracks/5SOA0gaKMMp9cgwn3nuwk7",
      id: "5SOA0gaKMMp9cgwn3nuwk7",
      name: "Solitude - Felsmann + Tiley Reinterpretation",
      popularity: 62,
      preview_url:
        "https://p.scdn.co/mp3-preview/3612941b358d94fbcc011708063ceae899348d8e?cid=0b297fa8a249464ba34f5861d4140e58",
      track_number: 1,
      type: "track",
      uri: "spotify:track:5SOA0gaKMMp9cgwn3nuwk7",
      is_local: false,
    },
    {
      album: {
        album_type: "ALBUM",
        total_tracks: 10,
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/4oL7pMxnb04uuRI7ReXmuh",
        },
        href: "https://api.spotify.com/v1/albums/4oL7pMxnb04uuRI7ReXmuh",
        id: "4oL7pMxnb04uuRI7ReXmuh",
        images: [
          {
            url: "https://i.scdn.co/image/ab67616d0000b27332f5fec7a879ed6ef28f0dfd",
            height: 640,
            width: 640,
          },
          {
            url: "https://i.scdn.co/image/ab67616d00001e0232f5fec7a879ed6ef28f0dfd",
            height: 300,
            width: 300,
          },
          {
            url: "https://i.scdn.co/image/ab67616d0000485132f5fec7a879ed6ef28f0dfd",
            height: 64,
            width: 64,
          },
        ],
        name: "Who Really Cares",
        release_date: "2016-02-25",
        release_date_precision: "day",
        type: "album",
        uri: "spotify:album:4oL7pMxnb04uuRI7ReXmuh",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/0Y6dVaC9DZtPNH4591M42W",
            },
            href: "https://api.spotify.com/v1/artists/0Y6dVaC9DZtPNH4591M42W",
            id: "0Y6dVaC9DZtPNH4591M42W",
            name: "TV Girl",
            type: "artist",
            uri: "spotify:artist:0Y6dVaC9DZtPNH4591M42W",
          },
        ],
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/0Y6dVaC9DZtPNH4591M42W",
          },
          href: "https://api.spotify.com/v1/artists/0Y6dVaC9DZtPNH4591M42W",
          id: "0Y6dVaC9DZtPNH4591M42W",
          name: "TV Girl",
          type: "artist",
          uri: "spotify:artist:0Y6dVaC9DZtPNH4591M42W",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 167864,
      explicit: true,
      external_ids: {
        isrc: "USCGH1682131",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/3IznIgmXtrUaoPWpQTy5jB",
      },
      href: "https://api.spotify.com/v1/tracks/3IznIgmXtrUaoPWpQTy5jB",
      id: "3IznIgmXtrUaoPWpQTy5jB",
      name: "Not Allowed",
      popularity: 84,
      preview_url:
        "https://p.scdn.co/mp3-preview/b1f61776e5425927fac6f4e79733d9fb8baf20dc?cid=0b297fa8a249464ba34f5861d4140e58",
      track_number: 5,
      type: "track",
      uri: "spotify:track:3IznIgmXtrUaoPWpQTy5jB",
      is_local: false,
    },
    {
      album: {
        album_type: "ALBUM",
        total_tracks: 15,
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/3kQpBS26lAj0A0VGl1snRl",
        },
        href: "https://api.spotify.com/v1/albums/3kQpBS26lAj0A0VGl1snRl",
        id: "3kQpBS26lAj0A0VGl1snRl",
        images: [
          {
            url: "https://i.scdn.co/image/ab67616d0000b273084051346f432cc68a1279cd",
            height: 640,
            width: 640,
          },
          {
            url: "https://i.scdn.co/image/ab67616d00001e02084051346f432cc68a1279cd",
            height: 300,
            width: 300,
          },
          {
            url: "https://i.scdn.co/image/ab67616d00004851084051346f432cc68a1279cd",
            height: 64,
            width: 64,
          },
        ],
        name: "Gunfighter Ballads And Trail Songs",
        release_date: "1959",
        release_date_precision: "year",
        type: "album",
        uri: "spotify:album:3kQpBS26lAj0A0VGl1snRl",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/0Xi59sEw38vRvwleSAVqoo",
            },
            href: "https://api.spotify.com/v1/artists/0Xi59sEw38vRvwleSAVqoo",
            id: "0Xi59sEw38vRvwleSAVqoo",
            name: "Marty Robbins",
            type: "artist",
            uri: "spotify:artist:0Xi59sEw38vRvwleSAVqoo",
          },
        ],
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/0Xi59sEw38vRvwleSAVqoo",
          },
          href: "https://api.spotify.com/v1/artists/0Xi59sEw38vRvwleSAVqoo",
          id: "0Xi59sEw38vRvwleSAVqoo",
          name: "Marty Robbins",
          type: "artist",
          uri: "spotify:artist:0Xi59sEw38vRvwleSAVqoo",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 235733,
      explicit: false,
      external_ids: {
        isrc: "USSM15901193",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/0AQquaENerGps8BQmbPw14",
      },
      href: "https://api.spotify.com/v1/tracks/0AQquaENerGps8BQmbPw14",
      id: "0AQquaENerGps8BQmbPw14",
      name: "Big Iron",
      popularity: 69,
      preview_url:
        "https://p.scdn.co/mp3-preview/b80beb7f651dd44d498e70082e57bd7a96f9fe7d?cid=0b297fa8a249464ba34f5861d4140e58",
      track_number: 1,
      type: "track",
      uri: "spotify:track:0AQquaENerGps8BQmbPw14",
      is_local: false,
    },
    {
      album: {
        album_type: "SINGLE",
        total_tracks: 1,
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/2w5lbvxycNKqfGSrWgmDpI",
        },
        href: "https://api.spotify.com/v1/albums/2w5lbvxycNKqfGSrWgmDpI",
        id: "2w5lbvxycNKqfGSrWgmDpI",
        images: [
          {
            url: "https://i.scdn.co/image/ab67616d0000b2730ad149b7241c212290bb11cf",
            height: 640,
            width: 640,
          },
          {
            url: "https://i.scdn.co/image/ab67616d00001e020ad149b7241c212290bb11cf",
            height: 300,
            width: 300,
          },
          {
            url: "https://i.scdn.co/image/ab67616d000048510ad149b7241c212290bb11cf",
            height: 64,
            width: 64,
          },
        ],
        name: "Hey Kids",
        release_date: "2018-04-20",
        release_date_precision: "day",
        type: "album",
        uri: "spotify:album:2w5lbvxycNKqfGSrWgmDpI",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/0pxhu7zSqPjBTUWMl6piHF",
            },
            href: "https://api.spotify.com/v1/artists/0pxhu7zSqPjBTUWMl6piHF",
            id: "0pxhu7zSqPjBTUWMl6piHF",
            name: "Molina",
            type: "artist",
            uri: "spotify:artist:0pxhu7zSqPjBTUWMl6piHF",
          },
        ],
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/0pxhu7zSqPjBTUWMl6piHF",
          },
          href: "https://api.spotify.com/v1/artists/0pxhu7zSqPjBTUWMl6piHF",
          id: "0pxhu7zSqPjBTUWMl6piHF",
          name: "Molina",
          type: "artist",
          uri: "spotify:artist:0pxhu7zSqPjBTUWMl6piHF",
        },
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/6P4APuruGUYRvwnzboQir3",
          },
          href: "https://api.spotify.com/v1/artists/6P4APuruGUYRvwnzboQir3",
          id: "6P4APuruGUYRvwnzboQir3",
          name: "Late Verlane",
          type: "artist",
          uri: "spotify:artist:6P4APuruGUYRvwnzboQir3",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 233374,
      explicit: false,
      external_ids: {
        isrc: "DKPF51800801",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/5poS8LyxohSACjuIZ61EyS",
      },
      href: "https://api.spotify.com/v1/tracks/5poS8LyxohSACjuIZ61EyS",
      id: "5poS8LyxohSACjuIZ61EyS",
      name: "Hey Kids",
      popularity: 68,
      preview_url:
        "https://p.scdn.co/mp3-preview/19511167d0398ca4c45ab5d9ca528ef8279855ae?cid=0b297fa8a249464ba34f5861d4140e58",
      track_number: 1,
      type: "track",
      uri: "spotify:track:5poS8LyxohSACjuIZ61EyS",
      is_local: false,
    },
    {
      album: {
        album_type: "ALBUM",
        total_tracks: 10,
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/3NB2cmFq9nyhHSVz0Zv08t",
        },
        href: "https://api.spotify.com/v1/albums/3NB2cmFq9nyhHSVz0Zv08t",
        id: "3NB2cmFq9nyhHSVz0Zv08t",
        images: [
          {
            url: "https://i.scdn.co/image/ab67616d0000b27331603889a9011b33a8d14b2c",
            height: 640,
            width: 640,
          },
          {
            url: "https://i.scdn.co/image/ab67616d00001e0231603889a9011b33a8d14b2c",
            height: 300,
            width: 300,
          },
          {
            url: "https://i.scdn.co/image/ab67616d0000485131603889a9011b33a8d14b2c",
            height: 64,
            width: 64,
          },
        ],
        name: "Strait From The Heart",
        release_date: "1982-01-01",
        release_date_precision: "day",
        type: "album",
        uri: "spotify:album:3NB2cmFq9nyhHSVz0Zv08t",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/5vngPClqofybhPERIqQMYd",
            },
            href: "https://api.spotify.com/v1/artists/5vngPClqofybhPERIqQMYd",
            id: "5vngPClqofybhPERIqQMYd",
            name: "George Strait",
            type: "artist",
            uri: "spotify:artist:5vngPClqofybhPERIqQMYd",
          },
        ],
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/5vngPClqofybhPERIqQMYd",
          },
          href: "https://api.spotify.com/v1/artists/5vngPClqofybhPERIqQMYd",
          id: "5vngPClqofybhPERIqQMYd",
          name: "George Strait",
          type: "artist",
          uri: "spotify:artist:5vngPClqofybhPERIqQMYd",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 173466,
      explicit: false,
      external_ids: {
        isrc: "USMC18212997",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/4TnUKixNWMfajncgdSwFoi",
      },
      href: "https://api.spotify.com/v1/tracks/4TnUKixNWMfajncgdSwFoi",
      id: "4TnUKixNWMfajncgdSwFoi",
      name: "Amarillo By Morning",
      popularity: 72,
      preview_url:
        "https://p.scdn.co/mp3-preview/35414eb9d89327fc8168fc4af83d73b776937539?cid=0b297fa8a249464ba34f5861d4140e58",
      track_number: 9,
      type: "track",
      uri: "spotify:track:4TnUKixNWMfajncgdSwFoi",
      is_local: false,
    },
    {
      album: {
        album_type: "SINGLE",
        total_tracks: 1,
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/4eadTzshRApGna6Ppz5XwO",
        },
        href: "https://api.spotify.com/v1/albums/4eadTzshRApGna6Ppz5XwO",
        id: "4eadTzshRApGna6Ppz5XwO",
        images: [
          {
            url: "https://i.scdn.co/image/ab67616d0000b273918207ec2316cec13a0e036f",
            height: 640,
            width: 640,
          },
          {
            url: "https://i.scdn.co/image/ab67616d00001e02918207ec2316cec13a0e036f",
            height: 300,
            width: 300,
          },
          {
            url: "https://i.scdn.co/image/ab67616d00004851918207ec2316cec13a0e036f",
            height: 64,
            width: 64,
          },
        ],
        name: "If We Ever Broke Up",
        release_date: "2023-02-10",
        release_date_precision: "day",
        type: "album",
        uri: "spotify:album:4eadTzshRApGna6Ppz5XwO",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/311uEW9rt5g2NmzjGEKS2E",
            },
            href: "https://api.spotify.com/v1/artists/311uEW9rt5g2NmzjGEKS2E",
            id: "311uEW9rt5g2NmzjGEKS2E",
            name: "Mae Stephens",
            type: "artist",
            uri: "spotify:artist:311uEW9rt5g2NmzjGEKS2E",
          },
        ],
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/311uEW9rt5g2NmzjGEKS2E",
          },
          href: "https://api.spotify.com/v1/artists/311uEW9rt5g2NmzjGEKS2E",
          id: "311uEW9rt5g2NmzjGEKS2E",
          name: "Mae Stephens",
          type: "artist",
          uri: "spotify:artist:311uEW9rt5g2NmzjGEKS2E",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 142758,
      explicit: true,
      external_ids: {
        isrc: "GBUM72300969",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/6maTPqynTmrkWIralgGaoP",
      },
      href: "https://api.spotify.com/v1/tracks/6maTPqynTmrkWIralgGaoP",
      id: "6maTPqynTmrkWIralgGaoP",
      name: "If We Ever Broke Up",
      popularity: 88,
      preview_url:
        "https://p.scdn.co/mp3-preview/792ab0581d7246b9f8975b70cba3a61879ef86e2?cid=0b297fa8a249464ba34f5861d4140e58",
      track_number: 1,
      type: "track",
      uri: "spotify:track:6maTPqynTmrkWIralgGaoP",
      is_local: false,
    },
    {
      album: {
        album_type: "ALBUM",
        total_tracks: 10,
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/7H5LNy2PyN3VLUm5nnMZEc",
        },
        href: "https://api.spotify.com/v1/albums/7H5LNy2PyN3VLUm5nnMZEc",
        id: "7H5LNy2PyN3VLUm5nnMZEc",
        images: [
          {
            url: "https://i.scdn.co/image/ab67616d0000b27382f846c52535bb65ab1d1a54",
            height: 640,
            width: 640,
          },
          {
            url: "https://i.scdn.co/image/ab67616d00001e0282f846c52535bb65ab1d1a54",
            height: 300,
            width: 300,
          },
          {
            url: "https://i.scdn.co/image/ab67616d0000485182f846c52535bb65ab1d1a54",
            height: 64,
            width: 64,
          },
        ],
        name: "A Decade Of Hits",
        release_date: "1973",
        release_date_precision: "year",
        type: "album",
        uri: "spotify:album:7H5LNy2PyN3VLUm5nnMZEc",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/12d4iIvTOk7JkI6ecvc3ca",
            },
            href: "https://api.spotify.com/v1/artists/12d4iIvTOk7JkI6ecvc3ca",
            id: "12d4iIvTOk7JkI6ecvc3ca",
            name: "The Charlie Daniels Band",
            type: "artist",
            uri: "spotify:artist:12d4iIvTOk7JkI6ecvc3ca",
          },
        ],
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/12d4iIvTOk7JkI6ecvc3ca",
          },
          href: "https://api.spotify.com/v1/artists/12d4iIvTOk7JkI6ecvc3ca",
          id: "12d4iIvTOk7JkI6ecvc3ca",
          name: "The Charlie Daniels Band",
          type: "artist",
          uri: "spotify:artist:12d4iIvTOk7JkI6ecvc3ca",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 214866,
      explicit: false,
      external_ids: {
        isrc: "USSM17900810",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/383Xl5QTigwj3QiA3Qc6S7",
      },
      href: "https://api.spotify.com/v1/tracks/383Xl5QTigwj3QiA3Qc6S7",
      id: "383Xl5QTigwj3QiA3Qc6S7",
      name: "The Devil Went Down to Georgia",
      popularity: 70,
      preview_url:
        "https://p.scdn.co/mp3-preview/db97d1a67debfcdf9d1c7921c85af469d88b1a6c?cid=0b297fa8a249464ba34f5861d4140e58",
      track_number: 1,
      type: "track",
      uri: "spotify:track:383Xl5QTigwj3QiA3Qc6S7",
      is_local: false,
    },
    {
      album: {
        album_type: "ALBUM",
        total_tracks: 30,
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/1ZXM9jY3Bsg12KXgwftBrO",
        },
        href: "https://api.spotify.com/v1/albums/1ZXM9jY3Bsg12KXgwftBrO",
        id: "1ZXM9jY3Bsg12KXgwftBrO",
        images: [
          {
            url: "https://i.scdn.co/image/ab67616d0000b273941001e5ce6bc1272466de29",
            height: 640,
            width: 640,
          },
          {
            url: "https://i.scdn.co/image/ab67616d00001e02941001e5ce6bc1272466de29",
            height: 300,
            width: 300,
          },
          {
            url: "https://i.scdn.co/image/ab67616d00004851941001e5ce6bc1272466de29",
            height: 64,
            width: 64,
          },
        ],
        name: "#1s ... and then some",
        release_date: "2009-09-08",
        release_date_precision: "day",
        type: "album",
        uri: "spotify:album:1ZXM9jY3Bsg12KXgwftBrO",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/0XKOBt59crntr7HQXXO8Yz",
            },
            href: "https://api.spotify.com/v1/artists/0XKOBt59crntr7HQXXO8Yz",
            id: "0XKOBt59crntr7HQXXO8Yz",
            name: "Brooks & Dunn",
            type: "artist",
            uri: "spotify:artist:0XKOBt59crntr7HQXXO8Yz",
          },
        ],
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/0XKOBt59crntr7HQXXO8Yz",
          },
          href: "https://api.spotify.com/v1/artists/0XKOBt59crntr7HQXXO8Yz",
          id: "0XKOBt59crntr7HQXXO8Yz",
          name: "Brooks & Dunn",
          type: "artist",
          uri: "spotify:artist:0XKOBt59crntr7HQXXO8Yz",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 198226,
      explicit: false,
      external_ids: {
        isrc: "USAN20900070",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/7Fq9RwQxSn3kW85PrDUf0M",
      },
      href: "https://api.spotify.com/v1/tracks/7Fq9RwQxSn3kW85PrDUf0M",
      id: "7Fq9RwQxSn3kW85PrDUf0M",
      name: "Boot Scootin' Boogie",
      popularity: 72,
      preview_url:
        "https://p.scdn.co/mp3-preview/c221b090acf0ca427df7148e20e00d23ea0a4410?cid=0b297fa8a249464ba34f5861d4140e58",
      track_number: 15,
      type: "track",
      uri: "spotify:track:7Fq9RwQxSn3kW85PrDUf0M",
      is_local: false,
    },
    {
      album: {
        album_type: "SINGLE",
        total_tracks: 5,
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/295qW3R6DSM1WfePwUpgux",
        },
        href: "https://api.spotify.com/v1/albums/295qW3R6DSM1WfePwUpgux",
        id: "295qW3R6DSM1WfePwUpgux",
        images: [
          {
            url: "https://i.scdn.co/image/ab67616d0000b273bd1c65fed5d5b87132ffe0c4",
            height: 640,
            width: 640,
          },
          {
            url: "https://i.scdn.co/image/ab67616d00001e02bd1c65fed5d5b87132ffe0c4",
            height: 300,
            width: 300,
          },
          {
            url: "https://i.scdn.co/image/ab67616d00004851bd1c65fed5d5b87132ffe0c4",
            height: 64,
            width: 64,
          },
        ],
        name: "recently",
        release_date: "2019-04-10",
        release_date_precision: "day",
        type: "album",
        uri: "spotify:album:295qW3R6DSM1WfePwUpgux",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/5zVu34ozw0BzXIcNHqkO0u",
            },
            href: "https://api.spotify.com/v1/artists/5zVu34ozw0BzXIcNHqkO0u",
            id: "5zVu34ozw0BzXIcNHqkO0u",
            name: "Liana Flores",
            type: "artist",
            uri: "spotify:artist:5zVu34ozw0BzXIcNHqkO0u",
          },
        ],
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/5zVu34ozw0BzXIcNHqkO0u",
          },
          href: "https://api.spotify.com/v1/artists/5zVu34ozw0BzXIcNHqkO0u",
          id: "5zVu34ozw0BzXIcNHqkO0u",
          name: "Liana Flores",
          type: "artist",
          uri: "spotify:artist:5zVu34ozw0BzXIcNHqkO0u",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 161929,
      explicit: false,
      external_ids: {
        isrc: "QZDA61986777",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/51Grh1RyUDcMBbpuyUIUHI",
      },
      href: "https://api.spotify.com/v1/tracks/51Grh1RyUDcMBbpuyUIUHI",
      id: "51Grh1RyUDcMBbpuyUIUHI",
      name: "rises the moon",
      popularity: 83,
      preview_url:
        "https://p.scdn.co/mp3-preview/8c17fd7d24c1f7fd551f7edc0f71054a9340fb3b?cid=0b297fa8a249464ba34f5861d4140e58",
      track_number: 1,
      type: "track",
      uri: "spotify:track:51Grh1RyUDcMBbpuyUIUHI",
      is_local: false,
    },
    {
      album: {
        album_type: "COMPILATION",
        total_tracks: 12,
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "HK",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/6XbZ0Hc2LQaLJuUaFrHfTY",
        },
        href: "https://api.spotify.com/v1/albums/6XbZ0Hc2LQaLJuUaFrHfTY",
        id: "6XbZ0Hc2LQaLJuUaFrHfTY",
        images: [
          {
            url: "https://i.scdn.co/image/ab67616d0000b273183cad608b1e5a734f052710",
            height: 640,
            width: 640,
          },
          {
            url: "https://i.scdn.co/image/ab67616d00001e02183cad608b1e5a734f052710",
            height: 300,
            width: 300,
          },
          {
            url: "https://i.scdn.co/image/ab67616d00004851183cad608b1e5a734f052710",
            height: 64,
            width: 64,
          },
        ],
        name: "C.W. McCall's Greatest Hits",
        release_date: "1990-01-01",
        release_date_precision: "day",
        type: "album",
        uri: "spotify:album:6XbZ0Hc2LQaLJuUaFrHfTY",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/0iTkPxRldzi5lmS6qZ70JV",
            },
            href: "https://api.spotify.com/v1/artists/0iTkPxRldzi5lmS6qZ70JV",
            id: "0iTkPxRldzi5lmS6qZ70JV",
            name: "C.W. McCall",
            type: "artist",
            uri: "spotify:artist:0iTkPxRldzi5lmS6qZ70JV",
          },
        ],
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/0iTkPxRldzi5lmS6qZ70JV",
          },
          href: "https://api.spotify.com/v1/artists/0iTkPxRldzi5lmS6qZ70JV",
          id: "0iTkPxRldzi5lmS6qZ70JV",
          name: "C.W. McCall",
          type: "artist",
          uri: "spotify:artist:0iTkPxRldzi5lmS6qZ70JV",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "HK",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 230600,
      explicit: false,
      external_ids: {
        isrc: "USPR37500034",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/6dGWq08LXuIw6T2oUeHECh",
      },
      href: "https://api.spotify.com/v1/tracks/6dGWq08LXuIw6T2oUeHECh",
      id: "6dGWq08LXuIw6T2oUeHECh",
      name: "Convoy",
      popularity: 61,
      preview_url:
        "https://p.scdn.co/mp3-preview/6a093f1c5ce5e657d58b02ee7e6ab7824dc9132b?cid=0b297fa8a249464ba34f5861d4140e58",
      track_number: 1,
      type: "track",
      uri: "spotify:track:6dGWq08LXuIw6T2oUeHECh",
      is_local: false,
    },
    {
      album: {
        album_type: "ALBUM",
        total_tracks: 11,
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/3XdvQjIMjdwxRivZrg1ziJ",
        },
        href: "https://api.spotify.com/v1/albums/3XdvQjIMjdwxRivZrg1ziJ",
        id: "3XdvQjIMjdwxRivZrg1ziJ",
        images: [
          {
            url: "https://i.scdn.co/image/ab67616d0000b273c289ed4316aaab5a5b7376c1",
            height: 640,
            width: 640,
          },
          {
            url: "https://i.scdn.co/image/ab67616d00001e02c289ed4316aaab5a5b7376c1",
            height: 300,
            width: 300,
          },
          {
            url: "https://i.scdn.co/image/ab67616d00004851c289ed4316aaab5a5b7376c1",
            height: 64,
            width: 64,
          },
        ],
        name: "The Gambler",
        release_date: "1978-11-20",
        release_date_precision: "day",
        type: "album",
        uri: "spotify:album:3XdvQjIMjdwxRivZrg1ziJ",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/4tw2Lmn9tTPUv7Gy7mVPI4",
            },
            href: "https://api.spotify.com/v1/artists/4tw2Lmn9tTPUv7Gy7mVPI4",
            id: "4tw2Lmn9tTPUv7Gy7mVPI4",
            name: "Kenny Rogers",
            type: "artist",
            uri: "spotify:artist:4tw2Lmn9tTPUv7Gy7mVPI4",
          },
        ],
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/4tw2Lmn9tTPUv7Gy7mVPI4",
          },
          href: "https://api.spotify.com/v1/artists/4tw2Lmn9tTPUv7Gy7mVPI4",
          id: "4tw2Lmn9tTPUv7Gy7mVPI4",
          name: "Kenny Rogers",
          type: "artist",
          uri: "spotify:artist:4tw2Lmn9tTPUv7Gy7mVPI4",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 214880,
      explicit: false,
      external_ids: {
        isrc: "USCN17800055",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/5KqldkCunQ2rWxruMEtGh0",
      },
      href: "https://api.spotify.com/v1/tracks/5KqldkCunQ2rWxruMEtGh0",
      id: "5KqldkCunQ2rWxruMEtGh0",
      name: "The Gambler",
      popularity: 76,
      preview_url:
        "https://p.scdn.co/mp3-preview/54da74f4132df927ea8e4400fc1614601aa0ee62?cid=0b297fa8a249464ba34f5861d4140e58",
      track_number: 1,
      type: "track",
      uri: "spotify:track:5KqldkCunQ2rWxruMEtGh0",
      is_local: false,
    },
    {
      album: {
        album_type: "ALBUM",
        total_tracks: 12,
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/5zi7WsKlIiUXv09tbGLKsE",
        },
        href: "https://api.spotify.com/v1/albums/5zi7WsKlIiUXv09tbGLKsE",
        id: "5zi7WsKlIiUXv09tbGLKsE",
        images: [
          {
            url: "https://i.scdn.co/image/ab67616d0000b2737005885df706891a3c182a57",
            height: 640,
            width: 640,
          },
          {
            url: "https://i.scdn.co/image/ab67616d00001e027005885df706891a3c182a57",
            height: 300,
            width: 300,
          },
          {
            url: "https://i.scdn.co/image/ab67616d000048517005885df706891a3c182a57",
            height: 64,
            width: 64,
          },
        ],
        name: "IGOR",
        release_date: "2019-05-17",
        release_date_precision: "day",
        type: "album",
        uri: "spotify:album:5zi7WsKlIiUXv09tbGLKsE",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/4V8LLVI7PbaPR0K2TGSxFF",
            },
            href: "https://api.spotify.com/v1/artists/4V8LLVI7PbaPR0K2TGSxFF",
            id: "4V8LLVI7PbaPR0K2TGSxFF",
            name: "Tyler, The Creator",
            type: "artist",
            uri: "spotify:artist:4V8LLVI7PbaPR0K2TGSxFF",
          },
        ],
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/4V8LLVI7PbaPR0K2TGSxFF",
          },
          href: "https://api.spotify.com/v1/artists/4V8LLVI7PbaPR0K2TGSxFF",
          id: "4V8LLVI7PbaPR0K2TGSxFF",
          name: "Tyler, The Creator",
          type: "artist",
          uri: "spotify:artist:4V8LLVI7PbaPR0K2TGSxFF",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 195320,
      explicit: true,
      external_ids: {
        isrc: "USQX91901115",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/0fv2KH6hac06J86hBUTcSf",
      },
      href: "https://api.spotify.com/v1/tracks/0fv2KH6hac06J86hBUTcSf",
      id: "0fv2KH6hac06J86hBUTcSf",
      name: "NEW MAGIC WAND",
      popularity: 84,
      preview_url:
        "https://p.scdn.co/mp3-preview/9ba2f7a5e848b2677beded6e4022043fc60e29e6?cid=0b297fa8a249464ba34f5861d4140e58",
      track_number: 6,
      type: "track",
      uri: "spotify:track:0fv2KH6hac06J86hBUTcSf",
      is_local: false,
    },
    {
      album: {
        album_type: "ALBUM",
        total_tracks: 14,
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/50ZenUP4O2Q5eCy2NRNvuz",
        },
        href: "https://api.spotify.com/v1/albums/50ZenUP4O2Q5eCy2NRNvuz",
        id: "50ZenUP4O2Q5eCy2NRNvuz",
        images: [
          {
            url: "https://i.scdn.co/image/ab67616d0000b2736ee35072df1af802cca09918",
            height: 640,
            width: 640,
          },
          {
            url: "https://i.scdn.co/image/ab67616d00001e026ee35072df1af802cca09918",
            height: 300,
            width: 300,
          },
          {
            url: "https://i.scdn.co/image/ab67616d000048516ee35072df1af802cca09918",
            height: 64,
            width: 64,
          },
        ],
        name: "Stick Season",
        release_date: "2022-10-14",
        release_date_precision: "day",
        type: "album",
        uri: "spotify:album:50ZenUP4O2Q5eCy2NRNvuz",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/2RQXRUsr4IW1f3mKyKsy4B",
            },
            href: "https://api.spotify.com/v1/artists/2RQXRUsr4IW1f3mKyKsy4B",
            id: "2RQXRUsr4IW1f3mKyKsy4B",
            name: "Noah Kahan",
            type: "artist",
            uri: "spotify:artist:2RQXRUsr4IW1f3mKyKsy4B",
          },
        ],
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/2RQXRUsr4IW1f3mKyKsy4B",
          },
          href: "https://api.spotify.com/v1/artists/2RQXRUsr4IW1f3mKyKsy4B",
          id: "2RQXRUsr4IW1f3mKyKsy4B",
          name: "Noah Kahan",
          type: "artist",
          uri: "spotify:artist:2RQXRUsr4IW1f3mKyKsy4B",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 194416,
      explicit: true,
      external_ids: {
        isrc: "USUM72217180",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/0jkzxxDG8z3Y5OmfNl1VM0",
      },
      href: "https://api.spotify.com/v1/tracks/0jkzxxDG8z3Y5OmfNl1VM0",
      id: "0jkzxxDG8z3Y5OmfNl1VM0",
      name: "Homesick",
      popularity: 73,
      preview_url:
        "https://p.scdn.co/mp3-preview/5154c11a8452b0940dcf0c64a3a672c32796cb0e?cid=0b297fa8a249464ba34f5861d4140e58",
      track_number: 12,
      type: "track",
      uri: "spotify:track:0jkzxxDG8z3Y5OmfNl1VM0",
      is_local: false,
    },
    {
      album: {
        album_type: "ALBUM",
        total_tracks: 21,
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/35qVMfUfBN6q2xzm9rZn5a",
        },
        href: "https://api.spotify.com/v1/albums/35qVMfUfBN6q2xzm9rZn5a",
        id: "35qVMfUfBN6q2xzm9rZn5a",
        images: [
          {
            url: "https://i.scdn.co/image/ab67616d0000b27388fed14b936c38007a302413",
            height: 640,
            width: 640,
          },
          {
            url: "https://i.scdn.co/image/ab67616d00001e0288fed14b936c38007a302413",
            height: 300,
            width: 300,
          },
          {
            url: "https://i.scdn.co/image/ab67616d0000485188fed14b936c38007a302413",
            height: 64,
            width: 64,
          },
        ],
        name: "INSIDE",
        release_date: "2021-06-10",
        release_date_precision: "day",
        type: "album",
        uri: "spotify:album:35qVMfUfBN6q2xzm9rZn5a",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/2Waw2sSbqvAwK8NwACNjVo",
            },
            href: "https://api.spotify.com/v1/artists/2Waw2sSbqvAwK8NwACNjVo",
            id: "2Waw2sSbqvAwK8NwACNjVo",
            name: "Bo Burnham",
            type: "artist",
            uri: "spotify:artist:2Waw2sSbqvAwK8NwACNjVo",
          },
        ],
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/2Waw2sSbqvAwK8NwACNjVo",
          },
          href: "https://api.spotify.com/v1/artists/2Waw2sSbqvAwK8NwACNjVo",
          id: "2Waw2sSbqvAwK8NwACNjVo",
          name: "Bo Burnham",
          type: "artist",
          uri: "spotify:artist:2Waw2sSbqvAwK8NwACNjVo",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 2,
      duration_ms: 301110,
      explicit: false,
      external_ids: {
        isrc: "USA2P2122059",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/5CU5CRWy6PjUJsHCVbkYI2",
      },
      href: "https://api.spotify.com/v1/tracks/5CU5CRWy6PjUJsHCVbkYI2",
      id: "5CU5CRWy6PjUJsHCVbkYI2",
      name: "That Funny Feeling",
      popularity: 63,
      preview_url:
        "https://p.scdn.co/mp3-preview/dde9472c8c64f77f1f2c80428d4461517436b070?cid=0b297fa8a249464ba34f5861d4140e58",
      track_number: 6,
      type: "track",
      uri: "spotify:track:5CU5CRWy6PjUJsHCVbkYI2",
      is_local: false,
    },
    {
      album: {
        album_type: "COMPILATION",
        total_tracks: 19,
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/7gzX88qS3Vx2r87g5pbdfJ",
        },
        href: "https://api.spotify.com/v1/albums/7gzX88qS3Vx2r87g5pbdfJ",
        id: "7gzX88qS3Vx2r87g5pbdfJ",
        images: [
          {
            url: "https://i.scdn.co/image/ab67616d0000b273a7e90e0f6a18e36a594d39c2",
            height: 640,
            width: 640,
          },
          {
            url: "https://i.scdn.co/image/ab67616d00001e02a7e90e0f6a18e36a594d39c2",
            height: 300,
            width: 300,
          },
          {
            url: "https://i.scdn.co/image/ab67616d00004851a7e90e0f6a18e36a594d39c2",
            height: 64,
            width: 64,
          },
        ],
        name: "O Brother, Where Art Thou? (Original Motion Picture Soundtrack)",
        release_date: "2000-12-05",
        release_date_precision: "day",
        type: "album",
        uri: "spotify:album:7gzX88qS3Vx2r87g5pbdfJ",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/0LyfQWJT6nXafLPZqxe9Of",
            },
            href: "https://api.spotify.com/v1/artists/0LyfQWJT6nXafLPZqxe9Of",
            id: "0LyfQWJT6nXafLPZqxe9Of",
            name: "Various Artists",
            type: "artist",
            uri: "spotify:artist:0LyfQWJT6nXafLPZqxe9Of",
          },
        ],
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/3T0CG1MKkAu9rxA2ezgyLC",
          },
          href: "https://api.spotify.com/v1/artists/3T0CG1MKkAu9rxA2ezgyLC",
          id: "3T0CG1MKkAu9rxA2ezgyLC",
          name: "The Soggy Bottom Boys",
          type: "artist",
          uri: "spotify:artist:3T0CG1MKkAu9rxA2ezgyLC",
        },
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/1eNxt1JI2Bgjl8bPDQ5sG8",
          },
          href: "https://api.spotify.com/v1/artists/1eNxt1JI2Bgjl8bPDQ5sG8",
          id: "1eNxt1JI2Bgjl8bPDQ5sG8",
          name: "Dan Tyminski",
          type: "artist",
          uri: "spotify:artist:1eNxt1JI2Bgjl8bPDQ5sG8",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 190000,
      explicit: false,
      external_ids: {
        isrc: "USMR10000050",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/0YwNdeDFbGP6AGwsQrtzdY",
      },
      href: "https://api.spotify.com/v1/tracks/0YwNdeDFbGP6AGwsQrtzdY",
      id: "0YwNdeDFbGP6AGwsQrtzdY",
      name: "I Am A Man Of Constant Sorrow - Radio Edit",
      popularity: 64,
      preview_url:
        "https://p.scdn.co/mp3-preview/4e0a46f7ab8c6a4f5a163f588c1f035d22a23ee7?cid=0b297fa8a249464ba34f5861d4140e58",
      track_number: 5,
      type: "track",
      uri: "spotify:track:0YwNdeDFbGP6AGwsQrtzdY",
      is_local: false,
    },
    {
      album: {
        album_type: "ALBUM",
        total_tracks: 58,
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/0BwWUstDMUbgq2NYONRqlu",
        },
        href: "https://api.spotify.com/v1/albums/0BwWUstDMUbgq2NYONRqlu",
        id: "0BwWUstDMUbgq2NYONRqlu",
        images: [
          {
            url: "https://i.scdn.co/image/ab67616d0000b273e52a59a28efa4773dd2bfe1b",
            height: 640,
            width: 640,
          },
          {
            url: "https://i.scdn.co/image/ab67616d00001e02e52a59a28efa4773dd2bfe1b",
            height: 300,
            width: 300,
          },
          {
            url: "https://i.scdn.co/image/ab67616d00004851e52a59a28efa4773dd2bfe1b",
            height: 64,
            width: 64,
          },
        ],
        name: "Rumours (Super Deluxe)",
        release_date: "1977-02-04",
        release_date_precision: "day",
        type: "album",
        uri: "spotify:album:0BwWUstDMUbgq2NYONRqlu",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/08GQAI4eElDnROBrJRGE0X",
            },
            href: "https://api.spotify.com/v1/artists/08GQAI4eElDnROBrJRGE0X",
            id: "08GQAI4eElDnROBrJRGE0X",
            name: "Fleetwood Mac",
            type: "artist",
            uri: "spotify:artist:08GQAI4eElDnROBrJRGE0X",
          },
        ],
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/08GQAI4eElDnROBrJRGE0X",
          },
          href: "https://api.spotify.com/v1/artists/08GQAI4eElDnROBrJRGE0X",
          id: "08GQAI4eElDnROBrJRGE0X",
          name: "Fleetwood Mac",
          type: "artist",
          uri: "spotify:artist:08GQAI4eElDnROBrJRGE0X",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 270213,
      explicit: false,
      external_ids: {
        isrc: "USWB11301116",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/5e9TFTbltYBg2xThimr0rU",
      },
      href: "https://api.spotify.com/v1/tracks/5e9TFTbltYBg2xThimr0rU",
      id: "5e9TFTbltYBg2xThimr0rU",
      name: "The Chain - 2004 Remaster",
      popularity: 83,
      preview_url:
        "https://p.scdn.co/mp3-preview/9cd01344e96f8dfaf0fb47fbb36d9da930daab2f?cid=0b297fa8a249464ba34f5861d4140e58",
      track_number: 7,
      type: "track",
      uri: "spotify:track:5e9TFTbltYBg2xThimr0rU",
      is_local: false,
    },
    {
      album: {
        album_type: "ALBUM",
        total_tracks: 13,
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/0mX8aXMM7nYOGUTGcTEeZH",
        },
        href: "https://api.spotify.com/v1/albums/0mX8aXMM7nYOGUTGcTEeZH",
        id: "0mX8aXMM7nYOGUTGcTEeZH",
        images: [
          {
            url: "https://i.scdn.co/image/ab67616d0000b273805374f00048ac081460cc70",
            height: 640,
            width: 640,
          },
          {
            url: "https://i.scdn.co/image/ab67616d00001e02805374f00048ac081460cc70",
            height: 300,
            width: 300,
          },
          {
            url: "https://i.scdn.co/image/ab67616d00004851805374f00048ac081460cc70",
            height: 64,
            width: 64,
          },
        ],
        name: "Horse of a Different Color",
        release_date: "2004-04-20",
        release_date_precision: "day",
        type: "album",
        uri: "spotify:album:0mX8aXMM7nYOGUTGcTEeZH",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/0oBEeN6BCxEgMogzThqrPf",
            },
            href: "https://api.spotify.com/v1/artists/0oBEeN6BCxEgMogzThqrPf",
            id: "0oBEeN6BCxEgMogzThqrPf",
            name: "Big & Rich",
            type: "artist",
            uri: "spotify:artist:0oBEeN6BCxEgMogzThqrPf",
          },
        ],
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/0oBEeN6BCxEgMogzThqrPf",
          },
          href: "https://api.spotify.com/v1/artists/0oBEeN6BCxEgMogzThqrPf",
          id: "0oBEeN6BCxEgMogzThqrPf",
          name: "Big & Rich",
          type: "artist",
          uri: "spotify:artist:0oBEeN6BCxEgMogzThqrPf",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 200306,
      explicit: false,
      external_ids: {
        isrc: "USWB10302758",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/5s7m2xNZWgz5FqVSIvJcGA",
      },
      href: "https://api.spotify.com/v1/tracks/5s7m2xNZWgz5FqVSIvJcGA",
      id: "5s7m2xNZWgz5FqVSIvJcGA",
      name: "Save a Horse (Ride a Cowboy)",
      popularity: 71,
      preview_url:
        "https://p.scdn.co/mp3-preview/da6ddf686f80a41f60d721e56c985999b93ab51b?cid=0b297fa8a249464ba34f5861d4140e58",
      track_number: 9,
      type: "track",
      uri: "spotify:track:5s7m2xNZWgz5FqVSIvJcGA",
      is_local: false,
    },
    {
      album: {
        album_type: "ALBUM",
        total_tracks: 12,
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/5zi7WsKlIiUXv09tbGLKsE",
        },
        href: "https://api.spotify.com/v1/albums/5zi7WsKlIiUXv09tbGLKsE",
        id: "5zi7WsKlIiUXv09tbGLKsE",
        images: [
          {
            url: "https://i.scdn.co/image/ab67616d0000b2737005885df706891a3c182a57",
            height: 640,
            width: 640,
          },
          {
            url: "https://i.scdn.co/image/ab67616d00001e027005885df706891a3c182a57",
            height: 300,
            width: 300,
          },
          {
            url: "https://i.scdn.co/image/ab67616d000048517005885df706891a3c182a57",
            height: 64,
            width: 64,
          },
        ],
        name: "IGOR",
        release_date: "2019-05-17",
        release_date_precision: "day",
        type: "album",
        uri: "spotify:album:5zi7WsKlIiUXv09tbGLKsE",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/4V8LLVI7PbaPR0K2TGSxFF",
            },
            href: "https://api.spotify.com/v1/artists/4V8LLVI7PbaPR0K2TGSxFF",
            id: "4V8LLVI7PbaPR0K2TGSxFF",
            name: "Tyler, The Creator",
            type: "artist",
            uri: "spotify:artist:4V8LLVI7PbaPR0K2TGSxFF",
          },
        ],
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/4V8LLVI7PbaPR0K2TGSxFF",
          },
          href: "https://api.spotify.com/v1/artists/4V8LLVI7PbaPR0K2TGSxFF",
          id: "4V8LLVI7PbaPR0K2TGSxFF",
          name: "Tyler, The Creator",
          type: "artist",
          uri: "spotify:artist:4V8LLVI7PbaPR0K2TGSxFF",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 375386,
      explicit: true,
      external_ids: {
        isrc: "USQX91901118",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/1hz7SRTGUNAtIQ46qiNv2p",
      },
      href: "https://api.spotify.com/v1/tracks/1hz7SRTGUNAtIQ46qiNv2p",
      id: "1hz7SRTGUNAtIQ46qiNv2p",
      name: "GONE, GONE / THANK YOU",
      popularity: 80,
      preview_url:
        "https://p.scdn.co/mp3-preview/bef1a42d0299c0f5a6b9be0bc604326038b50995?cid=0b297fa8a249464ba34f5861d4140e58",
      track_number: 10,
      type: "track",
      uri: "spotify:track:1hz7SRTGUNAtIQ46qiNv2p",
      is_local: false,
    },
    {
      album: {
        album_type: "ALBUM",
        total_tracks: 12,
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/1kd7QnBNMg5kygoclVuDqZ",
        },
        href: "https://api.spotify.com/v1/albums/1kd7QnBNMg5kygoclVuDqZ",
        id: "1kd7QnBNMg5kygoclVuDqZ",
        images: [
          {
            url: "https://i.scdn.co/image/ab67616d0000b2730cf212ffc3719550dfab899d",
            height: 640,
            width: 640,
          },
          {
            url: "https://i.scdn.co/image/ab67616d00001e020cf212ffc3719550dfab899d",
            height: 300,
            width: 300,
          },
          {
            url: "https://i.scdn.co/image/ab67616d000048510cf212ffc3719550dfab899d",
            height: 64,
            width: 64,
          },
        ],
        name: "I Walk the Line (Stereo Version)",
        release_date: "1964-06-13",
        release_date_precision: "day",
        type: "album",
        uri: "spotify:album:1kd7QnBNMg5kygoclVuDqZ",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/6kACVPfCOnqzgfEF5ryl0x",
            },
            href: "https://api.spotify.com/v1/artists/6kACVPfCOnqzgfEF5ryl0x",
            id: "6kACVPfCOnqzgfEF5ryl0x",
            name: "Johnny Cash",
            type: "artist",
            uri: "spotify:artist:6kACVPfCOnqzgfEF5ryl0x",
          },
        ],
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/6kACVPfCOnqzgfEF5ryl0x",
          },
          href: "https://api.spotify.com/v1/artists/6kACVPfCOnqzgfEF5ryl0x",
          id: "6kACVPfCOnqzgfEF5ryl0x",
          name: "Johnny Cash",
          type: "artist",
          uri: "spotify:artist:6kACVPfCOnqzgfEF5ryl0x",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 154173,
      explicit: false,
      external_ids: {
        isrc: "USSM16401289",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/3X9tJw6z5LowFx339fhTvu",
      },
      href: "https://api.spotify.com/v1/tracks/3X9tJw6z5LowFx339fhTvu",
      id: "3X9tJw6z5LowFx339fhTvu",
      name: "I Walk the Line - Stereo Version",
      popularity: 53,
      preview_url:
        "https://p.scdn.co/mp3-preview/6753cc5beef04aa3e2787662d4e706b0df65d436?cid=0b297fa8a249464ba34f5861d4140e58",
      track_number: 1,
      type: "track",
      uri: "spotify:track:3X9tJw6z5LowFx339fhTvu",
      is_local: false,
    },
    {
      album: {
        album_type: "ALBUM",
        total_tracks: 7,
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/49iT8dV8hZ5o7bqpOI5yfI",
        },
        href: "https://api.spotify.com/v1/albums/49iT8dV8hZ5o7bqpOI5yfI",
        id: "49iT8dV8hZ5o7bqpOI5yfI",
        images: [
          {
            url: "https://i.scdn.co/image/ab67616d0000b27334702dd79ebdfb24ffbefb53",
            height: 640,
            width: 640,
          },
          {
            url: "https://i.scdn.co/image/ab67616d00001e0234702dd79ebdfb24ffbefb53",
            height: 300,
            width: 300,
          },
          {
            url: "https://i.scdn.co/image/ab67616d0000485134702dd79ebdfb24ffbefb53",
            height: 64,
            width: 64,
          },
        ],
        name: "Public Void",
        release_date: "2020-09-25",
        release_date_precision: "day",
        type: "album",
        uri: "spotify:album:49iT8dV8hZ5o7bqpOI5yfI",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/3u6lPufHw4Oww6D88rv6sB",
            },
            href: "https://api.spotify.com/v1/artists/3u6lPufHw4Oww6D88rv6sB",
            id: "3u6lPufHw4Oww6D88rv6sB",
            name: "Penelope Scott",
            type: "artist",
            uri: "spotify:artist:3u6lPufHw4Oww6D88rv6sB",
          },
        ],
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/3u6lPufHw4Oww6D88rv6sB",
          },
          href: "https://api.spotify.com/v1/artists/3u6lPufHw4Oww6D88rv6sB",
          id: "3u6lPufHw4Oww6D88rv6sB",
          name: "Penelope Scott",
          type: "artist",
          uri: "spotify:artist:3u6lPufHw4Oww6D88rv6sB",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 194165,
      explicit: true,
      external_ids: {
        isrc: "QZK6F2019397",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/4blPH3Uy89WnOnYlIv7Ev4",
      },
      href: "https://api.spotify.com/v1/tracks/4blPH3Uy89WnOnYlIv7Ev4",
      id: "4blPH3Uy89WnOnYlIv7Ev4",
      name: "Rät",
      popularity: 74,
      preview_url:
        "https://p.scdn.co/mp3-preview/5814b457d6cfbbf60bef0a043ce9bb4f8fdc33c4?cid=0b297fa8a249464ba34f5861d4140e58",
      track_number: 7,
      type: "track",
      uri: "spotify:track:4blPH3Uy89WnOnYlIv7Ev4",
      is_local: false,
    },
  ],
};
