import { Nav } from "@/components/Nav";
import { Inter } from "next/font/google";
import "./globals.css";
import AppWriteWrapper from "@/context/appwriteWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AppWriteWrapper>
      <html lang="en">
        <body className={inter.className}>
          <Nav />
          {children}
        </body>
      </html>
    </AppWriteWrapper>
  );
}
